# Generated by Django 5.1.5 on 2025-01-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchentry',
            options={'verbose_name_plural': 'Match Entries'},
        ),
        migrations.AddField(
            model_name='matchentry',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
