# Generated by Django 5.1.5 on 2025-01-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0002_alter_matchentry_options_matchentry_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchentry',
            name='summary',
            field=models.JSONField(default=dict),
        ),
    ]
