# Generated by Django 5.1.5 on 2025-01-31 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0003_alter_matchentry_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchentry',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=128),
        ),
    ]
