# Generated by Django 5.1.5 on 2025-02-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0005_matchentry_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchentry',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('helicopter', 'AttackHelicopter'), ('non-binary', 'Non-binary'), ('transgender', 'Transgender'), ('genderqueer', 'Genderqueer'), ('genderfluid', 'Genderfluid'), ('agender', 'Agender'), ('other', 'Other'), ('prefer-not', 'Prefer not to say')], max_length=128),
        ),
    ]
