# Generated by Django 5.1.5 on 2025-02-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0006_alter_matchentry_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchentry',
            name='score',
            field=models.IntegerField(default=3357),
            preserve_default=False,
        ),
    ]
