# Generated by Django 5.1.5 on 2025-02-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0008_matchentry_permission_to_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchentry',
            name='response',
            field=models.JSONField(default=list),
        ),
    ]
