# Generated by Django 5.1.5 on 2025-02-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0009_matchentry_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchentry',
            name='response',
        ),
    ]
