# Generated by Django 5.1.5 on 2025-02-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0011_matchentry_classof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchentry',
            name='classof',
            field=models.IntegerField(default=2028),
        ),
    ]
