# Generated by Django 5.1.5 on 2025-02-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0012_alter_matchentry_classof'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchentry',
            name='opp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_entries', to='MatchEntry.matchentry'),
        ),
    ]
