# Generated by Django 5.1.5 on 2025-02-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchEntry', '0013_matchentry_opp'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchentry',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
